version: '3'

volumes:
  keycloak_data:
    driver: local
  
services:
  keycloak:
    image: manaty/keycloak
    container_name: keycloak
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data/keycloakdb
    environment:
      KEYCLOAK_USER: meveo.admin
      KEYCLOAK_PASSWORD: meveo
    ports:
      - 8081:8080
  